### ISSUE TITLE
Progress on Chromium 88

### ISSUE THREAD

**Issue by ghost** [ungoogled-software/ungoogled-chromium-debian#197]
I have finished the work on `debian_sid`. I am now waiting to see how the OBS test repository fares.

**Comment by ghost** [comment]
`debian_sid` has been tagged. Now working on `debian_buster`.

**Comment by ghost** [comment]
`debian_buster` is now building on OBS. I am waiting to see now how the OBS test repository fares.

**Comment by zaza42** [comment]
I can't compile on Debian sid, always stucked at:
```
ninja -j26 -C out/Release chrome chrome_sandbox content_shell chromedriver
ninja: Entering directory `out/Release'
[11614/44037] CXX obj/sql/sql/module.o
FAILED: obj/sql/sql/module.o 
clang++-11 -MMD -MF obj/sql/sql/module.o.d -DIS_SQL_IMPL -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-12-init-11462-g418f18c6-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DSQLITE_OMIT_ANALYZE -DSQLITE_OMIT_AUTOINIT -DSQLITE_OMIT_AUTORESET -DSQLITE_OMIT_COMPILEOPTION_DIAGS -DSQLITE_OMIT_COMPLETE -DSQLITE_OMIT_EXPLAIN -DSQLITE_OMIT_GET_TABLE -DSQLITE_DEFAULT_LOOKASIDE=0,0 -DSQLITE_OMIT_LOOKASIDE -DSQLITE_OMIT_TCL_VARIABLE -DSQLITE_OMIT_REINDEX -DSQLITE_OMIT_TRACE -DSQLITE_OMIT_UPSERT -DSQLITE_OMIT_WINDOWFUNC -DSQLITE_ENABLE_FTS3 -DSQLITE_DISABLE_FTS3_UNICODE -DSQLITE_DISABLE_FTS4_DEFERRED -DSQLITE_ENABLE_ICU -DSQLITE_SECURE_DELETE -DSQLITE_THREADSAFE=1 -DSQLITE_MAX_WORKER_THREADS=0 -DSQLITE_MAX_MMAP_SIZE=268435456 -DSQLITE_DEFAULT_FILE_PERMISSIONS=0600 -DSQLITE_DEFAULT_LOCKING_MODE=1 -DSQLITE_DEFAULT_MEMSTATUS=1 -DSQLITE_DEFAULT_PAGE_SIZE=4096 -DSQLITE_DEFAULT_PCACHE_INITSZ=0 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_USE_ALLOCA -DSQLITE_OMIT_DECLTYPE -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_HAVE_ISNAN -DSQLITE_ENABLE_BATCH_ATOMIC_WRITE -DSQLITE_TEMP_STORE=3 -DSQLITE_ENABLE_LOCKING_STYLE=0 -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/zlib_shim -Igen/shim_headers/libevent_shim -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wmax-tokens -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.1 -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.1 -O2 -fdebug-prefix-map=/usr/src/sources/2021/browser/uc88/build/src=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-conversion -Wno-unused-function -Wno-unused-variable -Wno-unused-private-field -Wno-deprecated-declarations -Wno-unreachable-code -Wno-unknown-pragmas -fno-delete-null-pointer-checks -c ../../sql/recover_module/module.cc -o obj/sql/sql/module.o
In file included from ../../sql/recover_module/module.cc:17:
../../sql/recover_module/cursor.h:65:5: error: static_assert failed due to requirement 'std::is_standard_layout<sql::recover::VirtualCursor>::value' "needed for the reinterpret_cast below"
    static_assert(std::is_standard_layout<VirtualCursor>::value,
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[11618/44037] CXX obj/sql/sql/table.o
FAILED: obj/sql/sql/table.o 
clang++-11 -MMD -MF obj/sql/sql/table.o.d -DIS_SQL_IMPL -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-12-init-11462-g418f18c6-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DSQLITE_OMIT_ANALYZE -DSQLITE_OMIT_AUTOINIT -DSQLITE_OMIT_AUTORESET -DSQLITE_OMIT_COMPILEOPTION_DIAGS -DSQLITE_OMIT_COMPLETE -DSQLITE_OMIT_EXPLAIN -DSQLITE_OMIT_GET_TABLE -DSQLITE_DEFAULT_LOOKASIDE=0,0 -DSQLITE_OMIT_LOOKASIDE -DSQLITE_OMIT_TCL_VARIABLE -DSQLITE_OMIT_REINDEX -DSQLITE_OMIT_TRACE -DSQLITE_OMIT_UPSERT -DSQLITE_OMIT_WINDOWFUNC -DSQLITE_ENABLE_FTS3 -DSQLITE_DISABLE_FTS3_UNICODE -DSQLITE_DISABLE_FTS4_DEFERRED -DSQLITE_ENABLE_ICU -DSQLITE_SECURE_DELETE -DSQLITE_THREADSAFE=1 -DSQLITE_MAX_WORKER_THREADS=0 -DSQLITE_MAX_MMAP_SIZE=268435456 -DSQLITE_DEFAULT_FILE_PERMISSIONS=0600 -DSQLITE_DEFAULT_LOCKING_MODE=1 -DSQLITE_DEFAULT_MEMSTATUS=1 -DSQLITE_DEFAULT_PAGE_SIZE=4096 -DSQLITE_DEFAULT_PCACHE_INITSZ=0 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_USE_ALLOCA -DSQLITE_OMIT_DECLTYPE -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_HAVE_ISNAN -DSQLITE_ENABLE_BATCH_ATOMIC_WRITE -DSQLITE_TEMP_STORE=3 -DSQLITE_ENABLE_LOCKING_STYLE=0 -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/zlib_shim -Igen/shim_headers/libevent_shim -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wmax-tokens -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.1 -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.1 -O2 -fdebug-prefix-map=/usr/src/sources/2021/browser/uc88/build/src=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-conversion -Wno-unused-function -Wno-unused-variable -Wno-unused-private-field -Wno-deprecated-declarations -Wno-unreachable-code -Wno-unknown-pragmas -fno-delete-null-pointer-checks -c ../../sql/recover_module/table.cc -o obj/sql/sql/table.o
In file included from ../../sql/recover_module/table.cc:11:
../../sql/recover_module/cursor.h:65:5: error: static_assert failed due to requirement 'std::is_standard_layout<sql::recover::VirtualCursor>::value' "needed for the reinterpret_cast below"
    static_assert(std::is_standard_layout<VirtualCursor>::value,
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[11627/44037] CXX obj/sql/sql/cursor.o
FAILED: obj/sql/sql/cursor.o 
clang++-11 -MMD -MF obj/sql/sql/cursor.o.d -DIS_SQL_IMPL -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-12-init-11462-g418f18c6-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -DSQLITE_OMIT_ANALYZE -DSQLITE_OMIT_AUTOINIT -DSQLITE_OMIT_AUTORESET -DSQLITE_OMIT_COMPILEOPTION_DIAGS -DSQLITE_OMIT_COMPLETE -DSQLITE_OMIT_EXPLAIN -DSQLITE_OMIT_GET_TABLE -DSQLITE_DEFAULT_LOOKASIDE=0,0 -DSQLITE_OMIT_LOOKASIDE -DSQLITE_OMIT_TCL_VARIABLE -DSQLITE_OMIT_REINDEX -DSQLITE_OMIT_TRACE -DSQLITE_OMIT_UPSERT -DSQLITE_OMIT_WINDOWFUNC -DSQLITE_ENABLE_FTS3 -DSQLITE_DISABLE_FTS3_UNICODE -DSQLITE_DISABLE_FTS4_DEFERRED -DSQLITE_ENABLE_ICU -DSQLITE_SECURE_DELETE -DSQLITE_THREADSAFE=1 -DSQLITE_MAX_WORKER_THREADS=0 -DSQLITE_MAX_MMAP_SIZE=268435456 -DSQLITE_DEFAULT_FILE_PERMISSIONS=0600 -DSQLITE_DEFAULT_LOCKING_MODE=1 -DSQLITE_DEFAULT_MEMSTATUS=1 -DSQLITE_DEFAULT_PAGE_SIZE=4096 -DSQLITE_DEFAULT_PCACHE_INITSZ=0 -DSQLITE_LIKE_DOESNT_MATCH_BLOBS -DSQLITE_OMIT_DEPRECATED -DSQLITE_OMIT_PROGRESS_CALLBACK -DSQLITE_OMIT_SHARED_CACHE -DSQLITE_USE_ALLOCA -DSQLITE_OMIT_DECLTYPE -DSQLITE_OMIT_LOAD_EXTENSION -DSQLITE_HAVE_ISNAN -DSQLITE_ENABLE_BATCH_ATOMIC_WRITE -DSQLITE_TEMP_STORE=3 -DSQLITE_ENABLE_LOCKING_STYLE=0 -I../.. -Igen -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/zlib_shim -Igen/shim_headers/libevent_shim -Igen/shim_headers/icui18n_shim -Igen/shim_headers/icuuc_shim -I../../third_party/abseil-cpp -I../../third_party/boringssl/src/include -I../../third_party/protobuf/src -Igen/protoc_out -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wmax-tokens -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.1 -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.1 -O2 -fdebug-prefix-map=/usr/src/sources/2021/browser/uc88/build/src=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-conversion -Wno-unused-function -Wno-unused-variable -Wno-unused-private-field -Wno-deprecated-declarations -Wno-unreachable-code -Wno-unknown-pragmas -fno-delete-null-pointer-checks -c ../../sql/recover_module/cursor.cc -o obj/sql/sql/cursor.o
In file included from ../../sql/recover_module/cursor.cc:5:
../../sql/recover_module/cursor.h:65:5: error: static_assert failed due to requirement 'std::is_standard_layout<sql::recover::VirtualCursor>::value' "needed for the reinterpret_cast below"
    static_assert(std::is_standard_layout<VirtualCursor>::value,
    ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
[11639/44037] CXX obj/testing/perf/perf/luci_test_result.o
ninja: build stopped: subcommand failed.
make[1]: *** [debian/rules:148: override_dh_auto_build-arch] Error 1
make[1]: Leaving directory '/usr/src/sources/2021/browser/uc88/build/src'
make: *** [debian/rules:122: binary] Error 2
dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2
```
This error is after another, that I was able to fix with this patch: https://bugs.gentoo.org/753239

**Comment by ghost** [comment]
It's not occurring in my container test builds nor on OBS. What's different about your environment? For that matter what commit are you using?

**Comment by zaza42** [comment]
I've followed the standard building steps: `git -C ungoogled-chromium-debian checkout --recurse-submodules debian_sid`
It downloaded `chromium-88.0.4324.146.tar.xz`

**Comment by ghost** [comment]
`debian_buster` has been tagged.

**Comment by riyad** [comment]
FWIW: I just tried the `88.0.4324.146-1.sid1` tag in order to see if I could get it to build on Ubuntu 20.10 (groovy) ... it almost did. All the dependencies installed without problems or incompatibilities.
But running `dpkg-buildpackage -b -uc` failed with the following error after a few seconds:

    [...]
    dpkg-source: info: applying system/use-desktop-gl-as-default.patch
    dpkg-source: info: applying inox-patchset/chromium-skia-harmony.patch
    dpkg-source: info: applying inox-patchset/fix-cfi-failures-with-unbundled-libxml.patch
    dpkg-source: info: applying fedora/enable-hardware-accelerated-mjpeg.patch
    dpkg-source: info: applying fedora/fix-vaapi-on-intel.patch
    dpkg-source: info: applying ungoogled-chromium/manpage.patch
    dpkg-source: info: applying ungoogled-chromium/safebrowsing.patch
    dpkg-source: info: applying ungoogled-chromium/explicit-python.patch
    dpkg-source: info: applying ungoogled-chromium/vpx19.patch
     debian/rules clean
    dh clean
       debian/rules override_dh_auto_clean
    make[1]: Entering directory '/home/ubuntu/build/src'
    rm -rf out
    find . -name \*.pyc -execdir rm -f {} \;
    dh_auto_clean
    make[1]: Leaving directory '/home/ubuntu/build/src'
       dh_clean
            rm -f debian/debhelper-build-stamp
            cp -an --reflink=auto debian/.debhelper/bucket/files/53979aeb23a0c60b3e9ca8539ae993e58e9f0298f667e28a142b49fb205c5ada debian/.debhelper/bucket/files/53979aeb23a0c60b3e9ca8539ae993e58e9f0298f667e28a142b49fb
    205c5ada.tmp                                                                                                                                                                                                                 mv debian/.debhelper/bucket/files/53979aeb23a0c60b3e9ca8539ae993e58e9f0298f667e28a142b49fb205c5ada.tmp build/src/third_party/breakpad/breakpad/autotools/config.guess
    dh_clean: error: mv debian/.debhelper/bucket/files/53979aeb23a0c60b3e9ca8539ae993e58e9f0298f667e28a142b49fb205c5ada.tmp build/src/third_party/breakpad/breakpad/autotools/config.guess: No such file or directory
    make: *** [debian/rules:122: clean] Error 255
    dpkg-buildpackage: error: debian/rules clean subprocess returned exit status 2 

But running `dpkg-buildpackage -b -uc -nc` immediately after that had no problems and went on compiling stuff for over an hour until this error:

    [...]
    [13767/44037] STAMP obj/third_party/webrtc/modules/video_coding/webrtc_vp8.inputdeps.stamp
    [13768/44037] CXX obj/third_party/webrtc/modules/video_coding/video_coding/frame_buffer2.o
    [13769/44037] CXX obj/third_party/webrtc/modules/video_coding/video_coding_utility/vp8_header_parser.o
    [13770/44037] CXX obj/third_party/webrtc/modules/video_coding/webrtc_vp8/libvpx_interface.o
    [13771/44037] CXX obj/third_party/webrtc/modules/video_coding/codecs/av1/libaom_av1_encoder/libaom_av1_encoder_absent.o
    [13772/44037] CXX obj/third_party/webrtc/modules/video_coding/webrtc_vp8/libvpx_vp8_decoder.o
    [13773/44037] CXX obj/third_party/webrtc/modules/video_coding/video_coding_utility/ivf_file_writer.o
    [13774/44037] CXX obj/third_party/webrtc/modules/video_coding/webrtc_vp8/libvpx_vp8_encoder.o
    FAILED: obj/third_party/webrtc/modules/video_coding/webrtc_vp8/libvpx_vp8_encoder.o 
    clang++-11 -MMD -MF obj/third_party/webrtc/modules/video_coding/webrtc_vp8/libvpx_vp8_encoder.o.d -DUSE_UDEV -DUSE_AURA=1 -DUSE_GLIB=1 -DUSE_NSS_CERTS=1 -DUSE_X11=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -DNO_UNWIND_TABLES -D_GNU_SOURCE -DCR_CLANG_REVISION=\"llvmorg-12-init-11462-g418f18c6-1\" -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D_FORTIFY_SOURCE=2 -DNDEBUG -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -DWEBRTC_ENABLE_PROTOBUF=1 -DRTC_ENABLE_VP9 -DHAVE_SCTP -DENABLE_EXTERNAL_AUTH -DHAVE_WEBRTC_VIDEO -DLOGGING_INSIDE_WEBRTC -DWEBRTC_LIBRARY_IMPL -DWEBRTC_ENABLE_AVX2 -DWEBRTC_NON_STATIC_TRACE_EVENT_HANDLERS=0 -DWEBRTC_CHROMIUM_BUILD -DWEBRTC_POSIX -DWEBRTC_LINUX -DABSL_ALLOCATOR_NOTHROW=1 -DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_40 -DGLIB_VERSION_MIN_REQUIRED=GLIB_VERSION_2_40 -I../.. -Igen -I../../third_party/webrtc_overrides -I../../third_party/webrtc -Igen/third_party/webrtc -I../../third_party/abseil-cpp -I../../third_party/perfetto/include -Igen/third_party/perfetto/build_config -Igen/third_party/perfetto -Igen/shim_headers/zlib_shim -Igen/shim_headers/libevent_shim -Igen/shim_headers/icui18n_shim -I../../third_party/libyuv/include -Igen/shim_headers/libvpx_shim -fno-strict-aliasing --param=ssp-buffer-size=4 -fstack-protector -fno-unwind-tables -fno-asynchronous-unwind-tables -fPIC -pthread -fcolor-diagnostics -fmerge-all-constants -fcrash-diagnostics-dir=../../tools/clang/crashreports -mllvm -instcombine-lower-dbg-declare=0 -m64 -march=x86-64 -Wno-builtin-macro-redefined -D__DATE__= -D__TIME__= -D__TIMESTAMP__= -Xclang -fdebug-compilation-dir -Xclang . -no-canonical-prefixes -Wall -Wextra -Wimplicit-fallthrough -Wunreachable-code -Wthread-safety -Wextra-semi -Wno-missing-field-initializers -Wno-unused-parameter -Wno-c++11-narrowing -Wno-unneeded-internal-declaration -Wno-undefined-var-template -Wno-psabi -Wno-ignored-pragma-optimize -Wno-implicit-int-float-conversion -Wno-final-dtor-non-final-class -Wno-builtin-assume-aligned-alignment -Wno-deprecated-copy -Wno-non-c-typedef-for-linkage -Wmax-tokens -fno-ident -fdata-sections -ffunction-sections -fno-omit-frame-pointer -g0 -ftrivial-auto-var-init=pattern -fvisibility=hidden -Wheader-hygiene -Wstring-conversion -Wtautological-overlap-compare -Wexit-time-destructors -Wglobal-constructors -Wno-shorten-64-to-32 -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -std=c++14 -fno-trigraphs -Wno-trigraphs -fno-exceptions -fno-rtti -fvisibility-inlines-hidden -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.0 -resource-dir=/usr/lib/llvm-11/lib/clang/11.0.0 -O2 -fdebug-prefix-map=/home/ubuntu/build/src=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-conversion -Wno-unused-function -Wno-unused-variable -Wno-unused-private-field -Wno-deprecated-declarations -Wno-unreachable-code -Wno-unknown-pragmas -fno-delete-null-pointer-checks -c ../../third_party/webrtc/modules/video_coding/codecs/vp8/libvpx_vp8_encoder.cc -o obj/third_party/webrtc/modules/video_coding/webrtc_vp8/libvpx_vp8_encoder.o
    ../../third_party/webrtc/modules/video_coding/codecs/vp8/libvpx_vp8_encoder.cc:1244:28: error: use of undeclared identifier 'VPX_IMG_FMT_NV12'; did you mean 'VPX_IMG_FMT_YV12'?
                    << (fmt == VPX_IMG_FMT_NV12 ? "NV12" : "I420");
                               ^~~~~~~~~~~~~~~~
                               VPX_IMG_FMT_YV12
    /usr/include/vpx/vpx_image.h:40:3: note: 'VPX_IMG_FMT_YV12' declared here
      VPX_IMG_FMT_YV12 =
      ^
    ../../third_party/webrtc/modules/video_coding/codecs/vp8/libvpx_vp8_encoder.cc:1291:26: error: use of undeclared identifier 'VPX_IMG_FMT_NV12'; did you mean 'VPX_IMG_FMT_YV12'?
      MaybeUpdatePixelFormat(VPX_IMG_FMT_NV12);
                             ^~~~~~~~~~~~~~~~
                             VPX_IMG_FMT_YV12
    /usr/include/vpx/vpx_image.h:40:3: note: 'VPX_IMG_FMT_YV12' declared here
      VPX_IMG_FMT_YV12 =
      ^
    2 errors generated.
    [13775/44037] CXX obj/third_party/webrtc/modules/video_coding/video_coding_utility/quality_scaler.o
    [13776/44037] CXX obj/third_party/webrtc/modules/video_coding/video_coding_utility/simulcast_utility.o
    [13777/44037] CXX obj/third_party/webrtc/modules/video_coding/video_coding_utility/simulcast_rate_allocator.o
    ninja: build stopped: subcommand failed.
    make[1]: *** [debian/rules:148: override_dh_auto_build-arch] Error 1
    make[1]: Leaving directory '/home/ubuntu/build/src'
    make: *** [debian/rules:122: binary] Error 2
    dpkg-buildpackage: error: debian/rules binary subprocess returned exit status 2

Well, this is out of my league. :sweat_smile: I just wanted document it. If any of you were going to look into it closer ... it would be appreciated. :slightly_smiling_face:

**Comment by ghost** [comment]
I've just compiled debian_sid at 3b481f1 with the latest ungoogled-chromium at f7c33de (88.0.4324.150) and it built just fine on Debian sid, and is running fine.

**Comment by black-reaver** [comment]
Does anyone know if the Ubuntu Bionic & Focal versions are still being maintained?

They're at 84.0.4147.135 & haven't been updated since August 2020.

**Comment by ghost** [comment]
Yes. I've been hit by extremely cold weather so I have had other priorities.

**Comment by ghost** [comment]
@Eloston I have discovered a problem with Bionic compatibility. We are no longer compatible with the available version of Node.JS. The only workaround I can find involves importing prebuilt ones into OBS which is already supported by the upstream build system. And those do not provide an i386 build.

So, I find myself asking the question, do we still want to maintain Bionic bionic albeit with one less architecture? Or do we want to drop it entirely?

It's becoming more difficult to keep patching it as it is. And Bionic's desktop support is only good for 3 years so it will be ending soon. Do we have any reasons to keep Bionic available for another 2 years?

**Comment by riyad** [comment]
For very selfish reasons I'd have no problems with ungoogled-chromium only being supported on Ubuntu's latest LTS and latest non-LTS releases. :wink: I have no preference for either "native"?!? or "unportable" as long as there's _something_ for those distros.

BTW: I appreciate all your hard work creating and updating patches, building and testing for all the variants. :clap: Chromium is a huge beast! My brain explodes just from watching it build and trying to "guesstimate" what all those components are good for ... HUGE respect! :1st_place_medal:

**Comment by LokiChaos** [comment]
I'll echo that supporting the latest LTS + non-LTS would be a sufficient goal. I'm going to guess most who don't migrate to the latest LTS are likely servers, not workstations where you'd be running Chromium.

Maybe a bit of a grace-period if nothing major breaks, but 20.04 has been out since last April.

**Comment by riyad** [comment]
FYI: the `ubuntu_focal` branch updated for 88 also builds successfully on Ubuntu Groovy. :v:

**Comment by cypherpunk1984** [comment]
I'm on Mint 18.3, so Bionic based, and I haven't been able to install any version after 84, because they need libc6 2.28 or newer, and Bionic is stuck on 2.27, and installing a non-official version of libc6 could pretty much break your whole system. I have tried deb files, AppImage files, etc. etc. nothing works. I love Ungoogled Chromium but is such a shame that I'm forced to upgrade to Focal for just one piece of software. What I don't understand is that Ubuntu's official repo has normal chromium-browser 88 for Bionic, I could install it, why doesn't it asks me for newer versions of libc6 and Ungoogled Chromium does?

**Comment by ghost** [comment]
> I'm on Mint 18.3, so Bionic based, and I haven't been able to install any version after 84, because they need libc6 2.28 or newer, and Bionic is stuck on 2.27, and installing a non-official version of libc6 could pretty much break your whole system. I have tried deb files, AppImage files, etc. etc. nothing works. I love Ungoogled Chromium but is such a shame that I'm forced to upgrade to Focal for just one piece of software. What I don't understand is that Ubuntu's official repo has normal chromium-browser 88 for Bionic, I could install it, why doesn't it asks me for newer versions of libc6 and Ungoogled Chromium does?

It doesn't actually. See here: https://packages.ubuntu.com/bionic/chromium-browser
It's still at 87, perhaps for the same reasons I ran into.

**Comment by cypherpunk1984** [comment]
> > I'm on Mint 18.3, so Bionic based, and I haven't been able to install any version after 84, because they need libc6 2.28 or newer, and Bionic is stuck on 2.27, and installing a non-official version of libc6 could pretty much break your whole system. I have tried deb files, AppImage files, etc. etc. nothing works. I love Ungoogled Chromium but is such a shame that I'm forced to upgrade to Focal for just one piece of software. What I don't understand is that Ubuntu's official repo has normal chromium-browser 88 for Bionic, I could install it, why doesn't it asks me for newer versions of libc6 and Ungoogled Chromium does?
> 
> It doesn't actually. See here: https://packages.ubuntu.com/bionic/chromium-browser
> It's still at 87, perhaps for the same reasons I ran into.

Oops I wrote 88 when I wanted to write 87. I still don't get why I can use v87 of normal chromium but not ungoogled chromium 87 (neither 85 or 86). Does only Ungoogled Chromium needs the newer libc6 versions, and normal chromium doesn't?

**Comment by ghost** [comment]
That has to do with when it was originally built. I can't find a way to make Bionic build so I am planning to drop our support for it soon. You may want to look into upgrading to Mint 19.x if you need an updated chromium. I should be able to fix the issues with Focal soon.

**Comment by cypherpunk1984** [comment]
Completely understandable.
I was planning to upgrade to Mint 20 in a couple of months, maybe I should just do it.
Thanks for your contributions!

**Comment by Eloston** [comment]
Closing since 88 has been out for a while.

**Comment by shvchk** [comment]
Wait, but production Focal repo is still on  84: https://build.opensuse.org/package/show/home:ungoogled_chromium/ungoogled-chromium-focal

**Comment by riyad** [comment]
hmm ... maybe builds were not triggered, because there're no focal/groovy tags for those releases?

**Comment by ghost** [comment]
I never managed to get it building so i never tagged it.
